name: Validación y Build con Docker

on:
  push:
    branches: [main]

jobs:
  validate-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio sin submódulos
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Jest directamente (sin chmod)
        run: node ./node_modules/jest/bin/jest.js

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validar y compilar imagen Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: eduardot0/hola-mundo:latest
